import { Router } from 'express';
import authRoutes from './auth';
import analysisRoutes from './analysis';
import productionManagementRoutes from './productionManagement';
import productionChartsRoutes from './productionCharts';
import planUploaderRoutes from './planUploader';
import dprAdcRoutes from './dprAdc';
import dprC4Routes from './dprC4';
import dprKdRoutes from './dprKd';
import mprAdcRoutes from './mprAdc';
import mprC4Routes from './mprC4';
import mprKdRoutes from './mprKd';
import palletEntryRoutes from './palletEntry';
import productMasterRoutes from './productMaster';
import kanbanMasterRoutes from './kanbanMaster';
import palletMasterRoutes from './palletMaster';
import locatorMasterRoutes from './locatorMaster';
import userMasterRoutes from './userMaster';
import preferenceMasterRoutes from './preferenceMaster';
import shiftMasterRoutes from './shiftMaster';
import ngMasterRoutes from './ngMaster';
import ngTaggingRoutes from './ngTagging';
import ngReportRoutes from './ngReport';
import dprMasterRoutes from './dprMaster';
import logsRoutes from './logs';
import healthRoutes from './health';
import settingsRoutes from './settings';

const router = Router();

router.use('/auth', authRoutes);
router.use('/analysis', analysisRoutes);
router.use('/production-management', productionManagementRoutes);
router.use('/production-charts', productionChartsRoutes);
router.use('/plan-uploader', planUploaderRoutes);
router.use('/dpr-adc', dprAdcRoutes);
router.use('/dpr-c4', dprC4Routes);
router.use('/dpr-kd', dprKdRoutes);
router.use('/mpr-adc', mprAdcRoutes);
router.use('/mpr-c4', mprC4Routes);
router.use('/mpr-kd', mprKdRoutes);
router.use('/pallet-entry', palletEntryRoutes);
router.use('/product-master', productMasterRoutes);
router.use('/kanban-master', kanbanMasterRoutes);
router.use('/pallet-master', palletMasterRoutes);
router.use('/locator-master', locatorMasterRoutes);
router.use('/user-master', userMasterRoutes);
router.use('/preference-master', preferenceMasterRoutes);
router.use('/shift-master', shiftMasterRoutes);
router.use('/ng-master', ngMasterRoutes);
router.use('/ng-tagging', ngTaggingRoutes);
router.use('/ng-report', ngReportRoutes);
router.use('/dpr-master', dprMasterRoutes);
router.use('/logs', logsRoutes);
router.use('/health', healthRoutes);
router.use('/settings', settingsRoutes);

export default router;
